[tool.poetry]
name = "fence"
version = "6.1.0"
description = "Gen3 AuthN/AuthZ OIDC Service"
authors = ["CTDS UChicago <cdis@uchicago.edu>"]
license = "Apache-2.0"
readme = "README.md"
repository = "https://github.com/uc-cdis/fence"
include = [
  "NOTICE",
]

[tool.poetry.dependencies]
python = "^3.6"
alembic = "^1.7.7"
authlib = "^0.11"
bcrypt = "^3.1.4"
boto3 = "~1.9.91"
botocore = "^1.12.253"
cached_property = "^1.5.1"
cdiserrors = "<2.0.0"
cdislogging = "^1.0.0"
cdispyutils = "^2.0.1"
cryptography = ">=3.2"
flask = ">=1.1.1"
flask-cors = "^3.0.3"
flask-restful = "^0.3.6"
flask_sqlalchemy_session = "^1.1"
email_validator = "^1.1.1"
gen3authz = "^1.5.1"
gen3cirrus = "^2.0.0"
gen3config = "^0.1.7"
gen3users = "^0.6.0"
idna = "^2.10" # https://github.com/python-poetry/poetry/issues/3555
markdown = "^3.1.1"
paramiko = "^2.6.0"
prometheus-client = "^0.9.0"
prometheus-flask-exporter = "^0.18.1"
psycopg2 = "^2.8.3"
pyjwt = "^1.5.3"
python_dateutil = "^2.6.1"
python-jose = "^2.0.2"
pyyaml = "^5.1"
requests = ">=2.18.0"
retry = "^0.9.2"
sqlalchemy = "^1.3.3"
storageclient = {git = "https://github.com/uc-cdis/storage-client", rev = "1.0.2"}
userdatamodel = "^2.4.0"
werkzeug = "^1.0.0"
cachelib = "^0.2.0"
azure-storage-blob = "^12.6.0"
Flask-WTF = "^0.14.3"
authutils = "6.1.0"


[tool.poetry.dev-dependencies]
addict = "^2.2.1"
cdisutilstest = {git = "https://github.com/uc-cdis/cdisutils-test", rev = "1.0.0"}
codacy-coverage = "^1.3.11"
coveralls = "^2.1.1"
mock = "^2.0.0"
moto = "^1.1.24"
pytest = "^3.2.3"
pytest-cov = "^2.5.1"
pytest-flask = "^0.15.0"
Flask-Cors = "^3.0.10"
Flask-RESTful = "^0.3.9"
Flask-SQLAlchemy-Session = "^1.1"
Flask = "^1.1.4"
Jinja2 = "^2.10.3"
Mako = "^1.1.6"
Markdown = "^3.3.7"
MarkupSafe = "^1.1.1"
PyJWT = "^1.7.1"
PyNaCl = "^1.5.0"
PyYAML = "^5.4.1"
SQLAlchemy = "^1.3.24"
SecretStorage = "^3.3.3"
WTForms = "^3.0.0"
Werkzeug = "^1.0.1"
aniso8601 = "^9.0.1"
async-generator = "^1.10"
atomicwrites = "^1.4.1"
attrs = "^22.1.0"
azure-core = "^1.24.2"
backoff = "^1.11.1"
boto = "^2.49.0"
cachetools = "^4.2.4"
certifi = "^2022.6.15"
cffi = "^1.15.1"
click = "^7.1.2"
contextvars = "^2.4"
coverage = "^5.5"
decorator = "^5.1.1"
dnspython = "^2.2.1"
docopt = "^0.6.2"
docutils = "^0.15.2"
ecdsa = "^0.18.0"
future = "^0.18.2"
google-api-core = "^1.32.0"
google-api-python-client = "^1.11.0"
google-auth-httplib2 = "^0.1.0"
google-auth = "^1.35.0"
google-cloud-core = "^2.3.1"
google-cloud-storage = "^1.44.0"
google-crc32c = "^1.3.0"
google-resumable-media = "^2.3.3"
googleapis-common-protos = "^1.56.3"
h11 = "^0.12.0"
httpcore = "^0.13.3"
httplib2 = "^0.20.4"
httpx = "^0.20.0"
immutables = "^0.18"
importlib-metadata = "^4.8.3"
iniconfig = "^1.1.1"
isodate = "^0.6.1"
itsdangerous = "^1.1.0"
jeepney = "^0.7.1"
jmespath = "^0.9.2"
keyring = "^22.3.0"
lockfile = "^0.12.2"
more-itertools = "^8.14.0"
msgpack = "^1.0.4"
msrest = "^0.7.1"
nose = "^1.3.7"
numpy = "^1.19.5"
oauth2client = "^3.0.0"
oauthlib = "^3.2.0"
packaging = "^21.3"
paramiko = "^2.11.0"
pbr = "^2.0.0"
pluggy = "^1.0.0"
protobuf = "^3.19.4"
py = "^1.11.0"
pyasn1-modules = "^0.2.8"
pyasn1 = "^0.4.8"
pycparser = "^2.21"
pycryptodome = "^3.15.0"
pyparsing = "^3.0.7"
pytz = "^2022.2.1"
requests-oauthlib = "^1.3.1"
requests = "^2.27.1"
responses = "^0.17.0"
retry = "^0.9.2"
rfc3986 = "^1.5.0"
rsa = "^4.9"
s3transfer = "^0.2.1"
six = "^1.16.0"
sniffio = "^1.2.0"
typing_extensions = "^4.1.1"
uritemplate = "^3.0.1"
urllib3 = "^1.25.11"
userdatamodel = "^2.4.0"
wheel = "^0.37.1"
xmltodict = "^0.13.0"
zipp = "^3.6.0"


[tool.poetry.scripts]
fence-create = 'bin.fence_create:main'

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
