name: CI

on: push

concurrency:
  group: '${{ github.workflow }} @ ${{ github.event.pull_request.head.label || github.head_ref || github.ref }}'
  cancel-in-progress: true


jobs:
  Security:
   runs-on: 'ubuntu-latest'
  # Superlint a simple combination of various linters, written in bash, to help validate source code.
  call-workflow-1-in-local-repo:
    uses: uc-cdis/.github/.github/workflows/lint.yaml@master
  # CodeQL is a simple Github native Static code analysis tool
  call-workflow2-in-local-repo:
    uses: uc-cdis/.github/.github/workflows/codeql-scan.yaml@master
  # Secrets detection is calling the Yelp Secrets Detector we use in pre-commit to ensure proper coverage
  secrets-detection:
    runs-on: 'ubuntu-latest'
    steps:
      - name: secrets detect
        uses: RobertFischer/detect-secrets-action@v2.0.0
      - name: Report Status
        if: always()
        uses: ravsamhq/notify-slack-action@v1
        with:
          status: ${{ job.status }}
          notify_when: 'failure'
          channel: infosec-alerts
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.ACTION_MONITORING_SLACK }}


  # Snyk native integration doesn't support poetry.lock files - this runs a check if a poetry.lock is found then runs a CLI scan to add coverage.
  file_existence:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v1

      - name: Check file existence
        id: check_files
        uses: andstor/file-existence-action@v1
        with:
          files: "poetry.lock"

      - name: File exists
        if: steps.check_files.outputs.files_exists == 'true'
        # Only runs if all of the files exists
        run: uc-cdis/.github/.github/actions/snykcli.yaml@master


  ci:
    name: Build Image and Push
    needs: Security
    uses: uc-cdis/.github/.github/workflows/image_build_push.yaml@master
    secrets:
      ECR_AWS_ACCESS_KEY_ID: ${{ secrets.ECR_AWS_ACCESS_KEY_ID }}
      ECR_AWS_SECRET_ACCESS_KEY: ${{ secrets.ECR_AWS_SECRET_ACCESS_KEY }}
      QUAY_USERNAME: ${{ secrets.QUAY_USERNAME }}
      QUAY_ROBOT_TOKEN: ${{ secrets.QUAY_ROBOT_TOKEN }}
