name: pytest-coverage-commentator
on:
  pull_request:
    branches:
      - '*'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install poetry coverage flake8 pytest pytest-cov
          if [ -f poetry.lock ]; then pip install -r poetry.lock; fi
      - name: Build coverage file
        run: |
          poetry run coverage report -m pytest --cache-clear --cov=app test/ > pytest-coverage.txt
      - name: Comment coverage
        uses: coroo/pytest-coverage-commentator@v1.0.2
