name: Run Fence unit tests
on: push

jobs:
  run_tests:
    uses: AidanHilt/.github/.github/workflows/python_unit_test.yaml@e3df21158f2fb75b8fc6d83bc43f2dda0876197e
    with:
      setup-script-location: https://raw.githubusercontent.com/AidanHilt/.github/master/unit_test_scripts/fence.sh
      dependency-file-location: https://raw.githubusercontent.com/AidanHilt/.github/master/requirements/fence_requirements.txt
