name: Run Fence unit tests
on: push

jobs:
  run_tests:
    runs-on: ubuntu-latest
    
    steps:
      - name: Run unit tests
        uses: AidanHilt/.github/workflows/python_unit_test.yaml@f32c1f7848d2d52dcba3882f58a56fe4f82f2b7a
        with:
          SETUP_SCRIPT_LOCATION: https://raw.githubusercontent.com/AidanHilt/.github/master/unit_test_scripts/fence.sh
