name: Run Fence unit tests
on: push

jobs:
  run_tests:
    uses: AidanHilt/.github/.github/workflows/python_unit_test.yaml@735d9ba847dea62dc82ff0ce4ae92c493a961d6d
    with:
      setup-script-location: https://raw.githubusercontent.com/AidanHilt/.github/master/unit_test_scripts/fence.sh
#comment
