name: Run Fence unit tests
on: push
jobs:
  run_tests:
    uses: uc-cdis/.github/.github/workflows/python_unit_test.yaml@25675353ab2e145ecea0fcc9e63f979e5f7f769e
    with:
      postgres-needed: 'false'
