name: Run Fence unit tests
on: push
#comment
jobs:
  run_tests:
    uses: uc-cdis/.github/.github/workflows/python_unit_test.yaml@c8f90611eeab45bfded5640a38a1c686ce0e461b
    with:
      setup-script-location: https://raw.githubusercontent.com/AidanHilt/.github/master/unit_test_scripts/fence.sh
