name: Run Fence unit tests
on: push

jobs:
  run_tests:
    uses: AidanHilt/.github/.github/workflows/python_unit_test.yaml@2b46f7382c126dd38cc576909c0dd6943bf2a66a
    with:
      setup-script-location: https://raw.githubusercontent.com/AidanHilt/.github/master/unit_test_scripts/fence.sh
#comment
